export enum Action {
    UPDATE_ACTIVE_TAB_NAME = 'UPDATE_ACTIVE_TAB_NAME',
    UPDATE_ACTIVE_HISTORY_TAB_NAME = 'UPDATE_ACTIVE_HISTORY_TAB_NAME',
    UPDATE_USER_DATA = 'UPDATE_USER_DATA',
    UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR'
}