export enum Action {
    UPDATE_ACTIVE_TAB_NAME = 'UPDATE_ACTIVE_TAB_NAME',
    UPDATE_ACTIVE_HISTORY_TAB_NAME = 'UPDATE_ACTIVE_HISTORY_TAB_NAME',
    UPDATE_NOTIFICATION_STATUS = 'UPDATE_NOTIFICATION_STATUS',
    UPDATE_USER_DATA = 'UPDATE_USER_DATA',
    UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR',
    UPDATE_LOADING = 'UPDATE_LOADING',
    UPDATE_ADMIN = 'UPDATE_ADMIN',
    UPDATE_LOGIN_FAILURE_MESSAGE = 'UPDATE_LOGIN_FAILURE_MESSAGE',
}